# Generated by Django 3.2 on 2023-05-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230501_1716'),
        ('reviews', '0003_auto_20230502_1420'),
    ]

    operations = [
    ]
